CREATE TABLE catalog (

 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 description TEXT NULL,
 price DECIMAL(12,2) NOT NULL,
 currency VARCHAR(5) NOT NULL,
 stock INT  NOT NULL DEFAULT 0 ,
 status VARCHAR(20) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP


);