CREATE TABLE payments (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
payment_id CHAR(36) UNIQUE NOT NULL,
order_reference VARCHAR(36),
order_id BIGINT NOT NULL,
amount DECIMAL(12,2) NOT NULL,
currency VARCHAR(5) NOT NULL,
status VARCHAR(20) NOT NULL,
method VARCHAR NOT NULL,
provider VARCHAR(50) NOT NULL,
provider_payment_id VARCHAR(100),
failure_reason VARCHAR(255),
retry_count INT,
idempotency_key VARCHAR NOT NULL UNIQUE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP





);